import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"
import ArticleCard from '../components/articles/articleCard'
import ProjectCard from '../components/projects/projectCard'
import ServiceCard from '../components/services/serviceCard'
import { getAllArticles, getAllProjects, getAllServices, getServices } from '../utils/api'

export default function Home(props) {
  const { projects, blogArticles, services } = props
  console.log("props", projects)



  return (
    <div className={styles.container}>
      <Head>
        <title>RoshanStudios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <main>
          <section className="site-section hero-section h-[80vh]">
            <div className="wrapper flex items-center justify-center h-full m-auto max-w-6xl">
              <header className="text-center md:w-2/3 md:mt-16 ">
                <h1 className="hero-text md:text-5xl ">
                Igniting Beautiful Innovation: Roshan Studios Unveils a World of Possibilities
                </h1>
                <p className="mb-4  mt-5">
                At our Shopify agency and UX design studio, we are driven by a passion for stunning innovation. We believe in taking a modern approach to deliver top-notch, premium services to our clients. The satisfaction our customers have experienced with our results so far speaks volumes about our commitment to excellence.
                </p>
                <Link href="/contact" passHref>
                  <button className="bg-gray-700 text-gray-50 py-1 px-3 rounded-md transform hover:scale-105 mt-10">
                    Get in touch
                  </button>
                </Link>
              </header>
            </div>
          </section>
          <section className="site-section services-section">
            <div className="wrapper m-auto py-6 max-w-6xl">
              <header className="relative grid md:grid-cols-3 gap-6 z-10 text-center">
                <div className="wrapper col-start-2">
                  <h1 className="header-text">Our Services</h1>
                  <p className="mb-16">
                    At Roshan Studios are obsessed with beautiful innovation.
                  </p>
                </div>
              </header>
              <div >
              <ul className="services grid md:grid-cols-3 gap-6 transform md:-translate-y-20 mt-10">
                <ServiceCard services={services} />
              </ul>
              </div>
            </div>
          </section>
          <section className="site-section projects-section">
            <div className="wrapper py-12 m-auto max-w-4xl">
              <header className="text-center mb-6">
                <h1 className="header-text">Our Projects</h1>
                <p>Here are some of the projects that we have worked on at Designli</p>
              </header>

              <ul className="action-cont text-center  ">
                <ProjectCard projects={projects} />
              </ul>
            </div>
          </section>
          <section className="site-section blog-section">
            <div className=" wrapper py-12 md:grid gap-8 grid-cols-7 items-center m-auto max-w-6xl">
              <header  className="md:grid col-start-1 col-end-3 mb-8">
                <h1 className="header-text">Our Blog</h1>
                <p className="mb-2">Helpful content from from the team to you.</p>
                <Link href="/blog" passHref>
                <button className="cta w-max">Explore our blog</button>
                </Link>
              </header>
              <ul className="articles md:grid gap-6 col-start-3 col-end-8">
                <ArticleCard articles={blogArticles} />
              </ul>
            </div>
          </section>
        </main>
      </>
    </div>
  )
}

export const getStaticProps = async () => {
  try {
    const [projects, blogArticles, services, servicesData] = await Promise.all([
      getAllProjects().catch(() => []),
      getAllArticles().catch(() => []),
      getAllServices().catch(() => []),
      getServices().catch(() => []),
    ])


    return {
      props: {
        projects,
        blogArticles,
        services,
        servicesData,
      },
    }
  } catch (error) {
    console.error("Error fetching data:", error)

    // Handle the error as needed, such as logging, sending alerts, etc.
    // Optionally, you can also return a custom error message or take alternative actions.
  }

  return {
    props: {
      projects: [],
      blogArticles: [],
      services: [],
      servicesData: [],
    },
  }
}
